name: WarZ
version: ${project.version}
main: com.github.beastyboo.warz.application.WarZPlugin
api-version: 1.16
authors: [ BeastyBoo ]
description: A warz plugin.
website: https://github.com/beastyboo
